### ISSUE TITLE
account for mobile views

### ISSUE THREAD

**Issue by TinaHeiligers** [TinaHeiligers/findmemore#28]
Change styled components to preprocessed css (saas or less are both fine)
Add break points for iPad and mobile

**Comment by maafaishal** [comment]
I have cloned your project. It is responsive on tablet & mobile, but not responsive on larger desktop. I have fixed it, please check my PR#36

**Comment by TinaHeiligers** [comment]
@maafaishal Thank you! I have reviewed your PR and barring one small syntax check error (I run my linter in a very specific way), it's great!
This is a side project I work on in my spare time and I haven't had much of that lately with too many conference talks to prepare, hence the outdated issue description.

**Comment by TinaHeiligers** [comment]
Closed with PR #38
