### ISSUE TITLE
Replace router

### ISSUE THREAD

**Issue by TinaHeiligers** [TinaHeiligers/findmemore#31]
The project currently uses Redux Little Router which was fine up to now but does not offer features planned for in the future. 
Replace the router with [connected-react-router](https://github.com/supasate/connected-react-router).

**Comment by flurmbo** [comment]
Hi Tina, can I work on this one?

**Comment by TinaHeiligers** [comment]
@flurmbo please do!

**Comment by TinaHeiligers** [comment]
Closed with #37
